export const actionTypes={
 LOAD_CONTENT:"LOAD_CONTENT",
 ADD_CONTENT:"ADD_CONTENT",
 GET_CONTENT:"GET_CONTENT",
 UPDATE_CONTENT:"UPDATE_CONTENT",
 DELETE_CONTENT:"DELETE_CONTENT",
 ADD_TO_HISTORY:"ADD_TO_HISTORY",
 REMOVE_FROM_HISTORY:"REMOVE_FROM_HISTORY",
 TOGGLE:"TOGGLE"
}